export * from "./Header/Header";
export * from "./Nav/Nav";
export * from "./Main/Main";
export * from "./Footer/Footer";
export * from "./Title/Title";
export * from "./CardParqueById/CardParqueById";
export * from "./CardParques/CardParques";
export * from "./CardAves/CardAves";
export * from "./CardAveById/CardAveById";